"""Build slide_manifest.csv for v2 presentation deck."""

from __future__ import annotations

from pathlib import Path
from typing import List

import pandas as pd

from .paths import PresentationPaths, default_paths

SLIDE_MANIFEST_ROWS = [
    {
        "slide_id": "S01",
        "slide_number": 1,
        "section": "intro",
        "title": "What distinguishes highly rated romance novels?",
        "subtitle": "Themes × narrative function × reader response",
        "evidence_level": "—",
        "main_message": "Research framing",
        "figure_id": "",
        "source_table": "manual",
        "speaker_takeaway": "Large-corpus computational question about reader appreciation",
        "appendix_link": "",
        "status": "manual",
        "build_mode": "manual",
    },
    {
        "slide_id": "S02",
        "slide_number": 2,
        "section": "intro",
        "title": "16,000 novels let us study reader appreciation at scale",
        "subtitle": "QUALITY vs REACH outcomes",
        "evidence_level": "METHOD",
        "main_message": "Corpus scale",
        "figure_id": "",
        "source_table": "corpus_stats.csv",
        "speaker_takeaway": "Two reader-response channels introduced",
        "appendix_link": "A01",
        "status": "data_only",
        "build_mode": "manual",
    },
    {
        "slide_id": "S03",
        "slide_number": 3,
        "section": "methods",
        "title": "From 115 million sentences to interpretable narrative measures",
        "subtitle": "Modeling → interpretation → analysis",
        "evidence_level": "METHOD",
        "main_message": "End-to-end pipeline",
        "figure_id": "",
        "source_table": "manual",
        "speaker_takeaway": "Contextual refinement is central",
        "appendix_link": "",
        "status": "manual",
        "build_mode": "manual",
    },
    {
        "slide_id": "S04",
        "slide_number": 4,
        "section": "methods",
        "title": "The final topic model was chosen as a trade-off, not by one metric",
        "subtitle": "Pareto selection among BO trials",
        "evidence_level": "METHOD",
        "main_message": "Model selection trade-off",
        "figure_id": "slide04_pareto_selection",
        "source_table": "slide04_pareto_points.csv",
        "speaker_takeaway": "Coherence alone can collapse granularity",
        "appendix_link": "A2",
        "status": "python",
        "build_mode": "python",
    },
    {
        "slide_id": "S05",
        "slide_number": 5,
        "section": "methods",
        "title": "A topic label is not yet a narrative interpretation",
        "subtitle": "BERTopic → LLM → taxonomy → contextual function",
        "evidence_level": "METHOD",
        "main_message": "Interpretation ladder",
        "figure_id": "",
        "source_table": "slide05_topic_card.csv",
        "speaker_takeaway": "Lexical patterns ≠ narrative function",
        "appendix_link": "",
        "status": "data_only",
        "build_mode": "manual",
    },
    {
        "slide_id": "S06",
        "slide_number": 6,
        "section": "methods",
        "title": "Context changed what the topics actually meant",
        "subtitle": "Lexical–contextual agreement + measurement repair",
        "evidence_level": "METHOD",
        "main_message": "Measurement audit",
        "figure_id": "slide06_context_measurement",
        "source_table": "slide06_agreement.csv; slide06_measurement.csv",
        "speaker_takeaway": "H2/H3 unmeasurable; H4 thin",
        "appendix_link": "",
        "status": "python",
        "build_mode": "python",
    },
    {
        "slide_id": "S07",
        "slide_number": 7,
        "section": "results",
        "title": "None of the six broad hypotheses produced a clean confirmatory win",
        "subtitle": "Prespecified |δ| ≥ 0.11 gate",
        "evidence_level": "CONFIRMATORY",
        "main_message": "Primary verdicts",
        "figure_id": "slide07_primary_verdict_cards",
        "source_table": "slide07_primary_verdicts.csv",
        "speaker_takeaway": "Broad binaries do not receive clean support",
        "appendix_link": "A3",
        "status": "python",
        "build_mode": "python",
    },
    {
        "slide_id": "S08",
        "slide_number": 8,
        "section": "results",
        "title": "Specific narrative functions reveal clearer differences",
        "subtitle": "Component-level Cliff's δ",
        "evidence_level": "CONFIRMATORY",
        "main_message": "Function-specific effects",
        "figure_id": "slide08_component_effects",
        "source_table": "slide08_component_effects.csv",
        "speaker_takeaway": "Reassurance, tenderness, appearance dominate",
        "appendix_link": "A5",
        "status": "python",
        "build_mode": "python",
    },
    {
        "slide_id": "S09",
        "slide_number": 9,
        "section": "results",
        "title": "Higher-rated romances devote relatively more space to tenderness",
        "subtitle": "Exploratory compositional shift",
        "evidence_level": "EXPLORATORY",
        "main_message": "Attention reallocation",
        "figure_id": "slide09_attention_shift",
        "source_table": "slide09_attention_shift.csv",
        "speaker_takeaway": "Tenderness up; explicit sex/appearance down",
        "appendix_link": "",
        "status": "python",
        "build_mode": "python",
    },
    {
        "slide_id": "S10",
        "slide_number": 10,
        "section": "results",
        "title": "What makes a book widely read is not what makes it highly rated",
        "subtitle": "Quality vs reach taxonomy leaves",
        "evidence_level": "EXPLORATORY",
        "main_message": "Two success channels diverge",
        "figure_id": "slide10_quality_reach_dumbbell",
        "source_table": "slide10_quality_reach.csv",
        "speaker_takeaway": "0 leaves clear both gates",
        "appendix_link": "A7",
        "status": "python",
        "build_mode": "python",
    },
    {
        "slide_id": "S11",
        "slide_number": 11,
        "section": "results",
        "title": "Better-rated books are not simply about more things",
        "subtitle": "Raw richness vs rarefaction vs suppression",
        "evidence_level": "EXPLORATORY",
        "main_message": "Richness is not a simple quality signal",
        "figure_id": "slide11_richness_evidence",
        "source_table": "slide11_richness_story.csv",
        "speaker_takeaway": "Thematic drivers matter more than breadth",
        "appendix_link": "A8",
        "status": "python",
        "build_mode": "python",
    },
    {
        "slide_id": "S12",
        "slide_number": 12,
        "section": "results",
        "title": "The exploratory extension shifts the question from topics to narrative experience",
        "subtitle": "Emotion, embodiment, social world",
        "evidence_level": "EXPLORATORY",
        "main_message": "EES frozen coding",
        "figure_id": "slide12_ees_integrated",
        "source_table": "slide12_ees_integrated.csv",
        "speaker_takeaway": "Containment signal; does not change H1–H6",
        "appendix_link": "A9",
        "status": "python",
        "build_mode": "python",
    },
    {
        "slide_id": "S13",
        "slide_number": 13,
        "section": "results",
        "title": "What do these statistical patterns look like in actual novels?",
        "subtitle": "Deterministic representative passages",
        "evidence_level": "EXPLORATORY",
        "main_message": "Textual grounding",
        "figure_id": "",
        "source_table": "slide13_representative_examples.csv",
        "speaker_takeaway": "Effects are about narrative attention types",
        "appendix_link": "",
        "status": "data_only",
        "build_mode": "manual",
    },
    {
        "slide_id": "S14",
        "slide_number": 14,
        "section": "conclusion",
        "title": "The signal is in how themes function, not just whether they occur",
        "subtitle": "Context, specificity, two channels",
        "evidence_level": "—",
        "main_message": "Three conclusions",
        "figure_id": "",
        "source_table": "manual",
        "speaker_takeaway": "Organization of narrative attention",
        "appendix_link": "",
        "status": "manual",
        "build_mode": "manual",
    },
]


def build_slide_manifest(paths: PresentationPaths | None = None) -> pd.DataFrame:
    paths = paths or default_paths()
    df = pd.DataFrame(SLIDE_MANIFEST_ROWS)
    paths.deck_manifests.mkdir(parents=True, exist_ok=True)
    df.to_csv(paths.deck_manifests / "slide_manifest.csv", index=False)
    return df


def write_figure_manifest(rows: List[dict], paths: PresentationPaths) -> Path:
    df = pd.DataFrame(rows)
    paths.deck_manifests.mkdir(parents=True, exist_ok=True)
    out = paths.deck_manifests / "figure_manifest.csv"
    df.to_csv(out, index=False)
    return out
